### ISSUE TITLE
Docs link is broken again

### ISSUE THREAD

**Issue by zion** [RobbieTheWagner/ember-shepherd#1684]
For anyone else searching it looks like it exists at the old location: https://robbiethewagner.github.io/ember-shepherd/docs

**Comment by RobbieTheWagner** [comment]
@zion seems like an easy PR, no?

**Comment by zion** [comment]
@RobbieTheWagner Sure! Wasn't sure if that was the desired docs location or not. 

https://github.com/RobbieTheWagner/ember-shepherd/pull/1689
